[package]
name = "marker"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.60", features = ["derive"] }
directories = "6.0.0"
serde = { version = "1.0.228", features = ["derive"] } 
serde_json = "1.0.149"
